CREATE COMPUTE POOL IF NOT EXISTS GPU_POOL
    MIN_NODES = 1
    MAX_NODES = 1
    INSTANCE_FAMILY = GPU_NV_M;

GRANT USAGE ON COMPUTE POOL GPU_POOL TO ROLE ENGINEER;

CREATE WAREHOUSE IF NOT EXISTS DEMO_WH;
GRANT USAGE ON WAREHOUSE DEMO_WH TO ROLE ENGINEER;

-- OPTIONAL: Create a separate database for easy cleanup
CREATE DATABASE IF NOT EXISTS LLM_DEMO;

GRANT USAGE ON DATABASE LLM_DEMO TO ROLE ENGINEER;
GRANT CREATE SCHEMA ON DATABASE LLM_DEMO TO ROLE ENGINEER;
GRANT CREATE STAGE ON SCHEMA LLM_DEMO.PUBLIC TO ROLE ENGINEER;
GRANT CREATE TABLE ON SCHEMA LLM_DEMO.PUBLIC TO ROLE ENGINEER;

-- Requires ACCOUNTADMIN privileges
CREATE OR REPLACE NETWORK RULE LLM_DEMO.PUBLIC.HUGGINGFACE_RULE
  MODE = 'EGRESS'
  TYPE = 'HOST_PORT'
  VALUE_LIST = (
    'huggingface.co:443',
    'www.huggingface.co:443',
    'cdn-lfs.huggingface.co:443',
    'cdn-lfs-us-1.huggingface.co:443'
  );

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION PYPI_HF_EAI
  ALLOWED_NETWORK_RULES = (
    SNOWFLAKE.EXTERNAL_ACCESS.PYPI_RULE,  -- Predefined rule from Snowflake
    LLM_DEMO.PUBLIC.HUGGINGFACE_RULE     -- Custom rule defined above
  )
  ENABLED = true;
GRANT USAGE ON INTEGRATION PYPI_HF_EAI TO ROLE ENGINEER;
