[project]
name = "mlops-101-online-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.5",
    "pre-commit>=4.2.0",
    "pyjwt>=2.10.1",
    "requests>=2.32.4",
]
